deploy: breaking changes, complete rework of arguements and defaults

diff --git a/multipress b/multipress
--- a/multipress
+++ b/multipress
@@ -1,46 +1,46 @@
 #!/usr/bin/env bash
+set -o errexit
 
 
 print_stderr() {
 	if [[ $1 == '0' ]]; then
-		[[ $2 ]] && printf "$2" "${@:3}" 1>&2
+		[[ $2 ]] && printf "$2" "${@:3}" 1>&2 || :
 	else
-		[[ $2 ]] && printf '%s'"$2" "ERROR: ${0##*/}, " "${@:3}" 1>&2
+		[[ $2 ]] && printf '%s'"$2" "ERROR: ${0##*/}, " "${@:3}" 1>&2 || :
 		exit "$1"
 	fi
 }
 
 
 
-delay_sec=
-instance_name=
-force_last=
+name=
+delim='__'
+activation_timeout='0.3'
+prevent_overrun=
 dry_run=
+command_segs=()
 while [[ "$1" ]]; do
 	case $1 in
-		--delay|-d)
-			shift; delay_sec=$1 ;;
-
-		--instance-name|-n)
-			shift; instance_name=$1 ;;
-
-		--force-last|-f)
-			force_last=1 ;;
-
-		--dry-run)
+		'--name'|'-n')
+			shift; name=$1 ;;
+		'--delim'|'-d')
+			shift; delim=$1 ;;
+		'--timeout'|'-t')
+			shift; activation_timeout=$1 ;;
+		'--prevent-overrun'|'-p')
+			prevent_overrun=1 ;;
+		'--dry-run')
 			dry_run=1 ;;
-
-		-*)
+		'--')
+			shift; break ;;
+		'-'*)
 			print_stderr 1 '%s\n' 'unrecognized option: '"$1" ;;
-
 		*)
-			# First non-option is the string that divides the exec groups
-			exec_divider=$1
-			shift
-			break
+			command_segs+=("$1")
 	esac
 	shift
 done
+command_segs+=("$@")
 
 
 
@@ -81,17 +81,17 @@ exec_pointer() {
 
 
 # Validate and define variables
-[[ $exec_divider ]] || print_stderr 1 'no command divider provided'
-[[ $1 ]] || print_stderr 1 'no command(s) provided'
-: ${delay_sec:='0.3'}
+[[ $delim ]] || print_stderr 1 'no command delimiter provided'
+[[ ${#command_segs[@]} != '0' ]] || print_stderr 1 'no command(s) provided'
+
 
 temp_dir=${TMPDIR:-${TEMPDIR:-${TMP:-${TEMP:-${XDG_RUNTIME_DIR:-/tmp}}}}}
-[[ -d $temp_dir ]] || print_stderr 1 'no temp directory found'
+[[ -d $temp_dir ]] || print_stderr 1 '%s\n' 'no suitable temp directory found'
 
 
 
 # Derive the fifo path from a checksum of the instance name or the exec portion of the parameters
-[[ $instance_name ]] && bashash_main "$instance_name" || bashash_main "$*"
+[[ $name ]] && bashash_main "$name" || bashash_main "${command_segs[*]}"
 fifo_path=$temp_dir'/'${0##*/}'__'$USER'_'$bashash__out
 
 
@@ -117,14 +117,14 @@ trap 'on_exit' 'EXIT'
 
 
 # Increment through the parameters defining the number of
-# exec dividers and where exec groups begin and end
+# exec delimiters and where exec groups begin and end
 exec_pos_start=()
 exec_pos_end=()
 exec_count=1
 param_pos=0
-for param in "$@"; do
+for param in "${command_segs[@]}"; do
 
-	if [[ $param == "$exec_divider" ]]; then
+	if [[ $param == "$delim" ]]; then
 		exec_pos_end[$exec_count]=$param_pos
 		(( param_pos++ ))
 		(( exec_count++ ))
@@ -141,7 +141,7 @@ done
 
 
 # If the last exec group is forced and there's only one, exec now
-[[ $force_last ]] && [[ $exec_count == '1' ]] && exec_pointer "$@"
+[[ $prevent_overrun ]] && [[ $exec_count == '1' ]] && exec_pointer "${command_segs[@]}"
 
 
 
@@ -149,11 +149,11 @@ done
 # increment the exec group pointer when a newline is read.
 # If the pointer exceeds the number exec groups then exit.
 exec_pointer=1
-while read -t "$delay_sec" -u 4; do
+while read -t "$activation_timeout" -u 4; do
 	(( exec_pointer++ ))
-	[[ $force_last ]] && (( exec_pointer == exec_count )) && break
+	[[ $prevent_overrun ]] && (( exec_pointer == exec_count )) && break
 done
-(( exec_pointer <= exec_count )) && exec_pointer "$@"
+(( exec_pointer <= exec_count )) && exec_pointer "${command_segs[@]}"
 
 
 
